### ISSUE TITLE
Trying to run it locally

### ISSUE THREAD

**Issue by panphora** [steadicat/swarmation#28]
I've got the server running, but I'm running into two issues:

http://localhost:3000/css/screen.css
http://localhost:3000/main.js

I can just run a preprocessor locally to handle the `styl` files, but I'm not sure why main.js isn't in the public directory. How do I set it up so I'm not getting a 404 on it?

**Comment by steadicat** [comment]
Did you try running `make dev` and then going to http://localhost:3000/?

**Comment by panphora** [comment]
This is the error I get:

```
Makefile:62: Secrets: No such file or directory
make: *** No rule to make target `Secrets'.  Stop.
```

**Comment by steadicat** [comment]
Just make an empty `Secrets` file in the root of the project:
```
$ touch Secrets
```

**Comment by panphora** [comment]
Thank you!
